print("Mill Creek Heterozygosity")
sfs_boot <- as.matrix(read.table("Mill_Bootstrap.sfs"))
hets <- apply(sfs_boot, 1, function(x) x[2] / sum(x))
print(mean(hets))
quantile(hets, c(.025,.975))

print("Mill Creek 2009 Heterozygosity")
sfs_boot <- as.matrix(read.table("Mill_2009_Bootstrap.sfs"))
hets <- apply(sfs_boot, 1, function(x) x[2] / sum(x))
print(mean(hets))
quantile(hets, c(.025,.975))

print("Hendrys Creek Heterozygosity")
sfs_boot <- as.matrix(read.table("Hendrys_Bootstrap.sfs"))
hets <- apply(sfs_boot, 1, function(x) x[2] / sum(x))
print(mean(hets))
quantile(hets, c(.025,.975))

print("Hendrys Creek 2009 Heterozygosity")
sfs_boot <- as.matrix(read.table("Hednrys_2009_Bootstrap.sfs"))
hets <- apply(sfs_boot, 1, function(x) x[2] / sum(x))
print(mean(hets))
quantile(hets, c(.025,.975))

print("Big Wash Creek Heterozygosity")
sfs_boot <- as.matrix(read.table("Bigwash_Bootstrap.sfs"))
hets <- apply(sfs_boot, 1, function(x) x[2] / sum(x))
print(mean(hets))
quantile(hets, c(.025,.975))

print("Big Wash Creek 2010 Heterozygosity")
sfs_boot <- as.matrix(read.table("Bigwash_2010_Bootstrap.sfs"))
hets <- apply(sfs_boot, 1, function(x) x[2] / sum(x))
print(mean(hets))
quantile(hets, c(.025,.975))

print("Deadman Creek Heterozygosity")
sfs_boot <- as.matrix(read.table("Deadman_Bootstrap.sfs"))
hets <- apply(sfs_boot, 1, function(x) x[2] / sum(x))
print(mean(hets))
quantile(hets, c(.025,.975))

print("Deadman Creek 2010 Heterozygosity")
sfs_boot <- as.matrix(read.table("Deadman_2010_Bootstrap.sfs"))
hets <- apply(sfs_boot, 1, function(x) x[2] / sum(x))
print(mean(hets))
quantile(hets, c(.025,.975))

print("South Big Wash Creek Heterozygosity")
sfs_boot <- as.matrix(read.table("South_BigWash_Bootstrap.sfs"))
hets <- apply(sfs_boot, 1, function(x) x[2] / sum(x))
print(mean(hets))
quantile(hets, c(.025,.975))

print("South Big Wash Creek 2010 Heterozygosity")
sfs_boot <- as.matrix(read.table("South_BigWash_2010_Bootstrap.sfs"))
hets <- apply(sfs_boot, 1, function(x) x[2] / sum(x))
print(mean(hets))
quantile(hets, c(.025,.975))

print("Willard Creek Heterozygosity")
sfs_boot <- as.matrix(read.table("Willard_Bootstrap.sfs"))
hets <- apply(sfs_boot, 1, function(x) x[2] / sum(x))
print(mean(hets))
quantile(hets, c(.025,.975))

print("Willard Creek 2003 Heterozygosity")
sfs_boot <- as.matrix(read.table("Willard_2003_Bootstrap.sfs"))
hets <- apply(sfs_boot, 1, function(x) x[2] / sum(x))
print(mean(hets))
quantile(hets, c(.025,.975))

print("Strawberry Creek Heterozygosity")
sfs_boot <- as.matrix(read.table("Strawberry_Bootstrap.sfs"))
hets <- apply(sfs_boot, 1, function(x) x[2] / sum(x))
print(mean(hets))
quantile(hets, c(.025,.975))

print("Strawberry Creek 2009 Heterozygosity")
sfs_boot <- as.matrix(read.table("Strawberry_2009_Bootstrap.sfs"))
hets <- apply(sfs_boot, 1, function(x) x[2] / sum(x))
print(mean(hets))
quantile(hets, c(.025,.975))

print("Smith Creek Heterozygosity")
sfs_boot <- as.matrix(read.table("Smith_Bootstrap.sfs"))
hets <- apply(sfs_boot, 1, function(x) x[2] / sum(x))
print(mean(hets))
quantile(hets, c(.025,.975))

print("Smith Creek 2009 Heterozygosity")
sfs_boot <- as.matrix(read.table("Smith_2009_Bootstrap.sfs"))
hets <- apply(sfs_boot, 1, function(x) x[2] / sum(x))
print(mean(hets))
quantile(hets, c(.025,.975))

print("South Baker Creek Heterozygosity")
sfs_boot <- as.matrix(read.table("South_Baker_Bootstrap.sfs"))
hets <- apply(sfs_boot, 1, function(x) x[2] / sum(x))
print(mean(hets))
quantile(hets, c(.025,.975))

print("South Baker Creek 2009 Heterozygosity")
sfs_boot <- as.matrix(read.table("South_Baker_2009_Bootstrap.sfs"))
hets <- apply(sfs_boot, 1, function(x) x[2] / sum(x))
print(mean(hets))
quantile(hets, c(.025,.975))
